//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public bus()
        {
            this.bus_trip = new HashSet<bus_trip>();
            this.drives = new HashSet<drive>();
        }
    
        public int bus_id { get; set; }
        public Nullable<int> bus_type_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual bus_type bus_type { get; set; }
        public virtual company company { get; set; }
        public virtual ICollection<bus_trip> bus_trip { get; set; }
        public virtual ICollection<drive> drives { get; set; }
    }
}
