//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_type
    {
        public bus_type()
        {
            this.buses = new HashSet<bus>();
        }
    
        public int bus_type_id { get; set; }
        public string bus_type_name { get; set; }
    
        public virtual ICollection<bus> buses { get; set; }
    }
}
