//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_trip
    {
        public int bus_trip_id { get; set; }
        public Nullable<System.DateTime> bus_trip_date { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<int> route_trip_id { get; set; }
        public Nullable<int> bus_id { get; set; }
        public Nullable<int> driver_id { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual route_trip route_trip { get; set; }
    }
}
