//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTrackingEntities : DbContext
    {
        public BusTrackingEntities()
            : base("name=BusTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<bus_trip> bus_trip { get; set; }
        public virtual DbSet<bus_type> bus_type { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<complaint> complaints { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<drive> drives { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<passes_through> passes_through { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<route_trip> route_trip { get; set; }
    }
}
