//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complaint
    {
        public int complaint_id { get; set; }
        public string complaint1 { get; set; }
        public Nullable<int> route_id { get; set; }
    }
}
