//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.buses = new HashSet<bus>();
        }
    
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public string company_phone_number { get; set; }
    
        public virtual ICollection<bus> buses { get; set; }
    }
}
