//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passes_through
    {
        public int passes_through_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<short> order_no { get; set; }
        public Nullable<System.TimeSpan> time_to_reach { get; set; }
    
        public virtual location location { get; set; }
        public virtual route route { get; set; }
    }
}
