//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrackingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_trip
    {
        public route_trip()
        {
            this.bus_trip = new HashSet<bus_trip>();
        }
    
        public int route_trip_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<short> number_of_trips { get; set; }
        public Nullable<System.TimeSpan> arrival_time { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
    
        public virtual ICollection<bus_trip> bus_trip { get; set; }
        public virtual route route { get; set; }
    }
}
